# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc

from __future__ import annotations

import importlib.util
from pathlib import Path
from textwrap import dedent

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "render_packaging.py"
SPEC = importlib.util.spec_from_file_location("render_packaging", SCRIPT)
assert SPEC is not None
render_packaging = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(render_packaging)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(text).lstrip(), encoding="utf-8")


def _fixture_root(tmp_path: Path, *, root_version: str = "1.2.3") -> Path:
    _write(
        tmp_path / "pyproject.toml",
        f"""
        [project]
        name = "solstone"
        version = "{root_version}"
        """,
    )
    for package_name in ("solstone-journal", "solstone-journal-cuda"):
        _write(
            tmp_path / "packages" / package_name / "pyproject.toml",
            f"""
            [project]
            name = "{package_name}"
            version = "0.0.1"
            dependencies = ["solstone[journal-host]==0.0.1"]
            """,
        )
    _write(
        tmp_path / "core" / "Cargo.toml",
        """
        [workspace]
        members = ["crates/solstone-core", "crates/solstone-core-cli"]
        resolver = "3"

        [workspace.package]
        version = "0.0.1"
        edition = "2024"
        rust-version = "1.85"
        license = "AGPL-3.0-only"

        [workspace.dependencies]
        solstone-core-cli = { path = "crates/solstone-core-cli" }
        """,
    )
    _write(
        tmp_path / "core" / "crates" / "solstone-core" / "Cargo.toml",
        """
        [package]
        name = "solstone-core"
        version.workspace = true
        edition.workspace = true
        rust-version.workspace = true
        license.workspace = true
        """,
    )
    _write(
        tmp_path / "core" / "crates" / "solstone-core-cli" / "Cargo.toml",
        """
        [package]
        name = "solstone-core-cli"
        version.workspace = true
        edition.workspace = true
        rust-version.workspace = true
        license.workspace = true
        """,
    )
    _write_cargo_lock(tmp_path, _cargo_lock_text())
    return tmp_path


def _write_cargo_lock(root: Path, text: str) -> None:
    _write(root / "core" / "Cargo.lock", text)


def _cargo_lock_text(*, cli_block: str | None = None) -> str:
    if cli_block is None:
        cli_block = """
        [[package]]
        name = "solstone-core-cli"
        version = "0.0.1"
        """
    core_block = dedent(
        """
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 4

        [[package]]
        name = "solstone-core"
        version = "0.0.1"
        dependencies = [
         "solstone-core-cli",
        ]
        """
    ).lstrip()
    return f"{core_block}\n{dedent(cli_block).strip()}\n"


def test_render_updates_python_leaves_and_cargo_lockstep(tmp_path: Path) -> None:
    root = _fixture_root(tmp_path, root_version="2.3.4")

    rendered = render_packaging.render(root)

    assert 'version = "2.3.4"' in rendered[root / "core" / "Cargo.toml"]
    assert (
        'name = "solstone-core"\nversion = "2.3.4"'
        in rendered[root / "core" / "Cargo.lock"]
    )
    assert (
        'name = "solstone-core-cli"\nversion = "2.3.4"'
        in rendered[root / "core" / "Cargo.lock"]
    )
    for package_name in ("solstone-journal", "solstone-journal-cuda"):
        leaf = rendered[root / "packages" / package_name / "pyproject.toml"]
        assert 'version = "2.3.4"' in leaf
        assert '"solstone[journal-host]==2.3.4"' in leaf


def test_render_raises_when_cargo_lock_is_missing_member_block(tmp_path: Path) -> None:
    root = _fixture_root(tmp_path)
    _write_cargo_lock(root, _cargo_lock_text(cli_block=""))

    with pytest.raises(render_packaging.PackagingRenderError, match="missing"):
        render_packaging.render(root)


def test_render_raises_when_cargo_lock_member_block_has_no_version(
    tmp_path: Path,
) -> None:
    root = _fixture_root(tmp_path)
    _write_cargo_lock(
        root,
        _cargo_lock_text(
            cli_block="""
            [[package]]
            name = "solstone-core-cli"
            """,
        ),
    )

    with pytest.raises(render_packaging.PackagingRenderError, match="version line"):
        render_packaging.render(root)


def test_render_raises_when_cargo_lock_member_block_has_source(
    tmp_path: Path,
) -> None:
    root = _fixture_root(tmp_path)
    _write_cargo_lock(
        root,
        _cargo_lock_text(
            cli_block="""
            [[package]]
            name = "solstone-core-cli"
            version = "0.0.1"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            """,
        ),
    )

    with pytest.raises(render_packaging.PackagingRenderError, match="source-less"):
        render_packaging.render(root)


def test_render_raises_when_cargo_lock_has_duplicate_member_block(
    tmp_path: Path,
) -> None:
    root = _fixture_root(tmp_path)
    duplicate = """
    [[package]]
    name = "solstone-core-cli"
    version = "0.0.1"

    [[package]]
    name = "solstone-core-cli"
    version = "0.0.1"
    """
    _write_cargo_lock(root, _cargo_lock_text(cli_block=duplicate))

    with pytest.raises(render_packaging.PackagingRenderError, match="duplicate"):
        render_packaging.render(root)
