[package]
name = "solstone-core-sol-client-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json = { workspace = true }
solstone-core-sol-client = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
