#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc

"""Render derived packaging metadata from the root pyproject version."""

from __future__ import annotations

import argparse
import logging
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROOT_PYPROJECT = ROOT / "pyproject.toml"
HOST_PYPROJECT = ROOT / "packages" / "solstone-journal-host" / "pyproject.toml"
HOST_PIN_RE = re.compile(r'(?P<quote>")solstone-journal-host==[^"]+(?P=quote)')
OPTIONAL_DEPS_RE = re.compile(
    r"(?ms)^\[project\.optional-dependencies\]\n(?P<body>.*?)(?=^\[|\Z)"
)
ARRAY_RE_TEMPLATE = r"(?ms)^(?P<prefix>{name}\s*=\s*\[\n)(?P<body>.*?)(?P<suffix>^\])"

LOGGER = logging.getLogger(__name__)


class PackagingRenderError(RuntimeError):
    """Raised when packaging metadata cannot be rendered safely."""


def _read_version(pyproject_text: str) -> str:
    data = tomllib.loads(pyproject_text)
    try:
        version = data["project"]["version"]
    except KeyError as exc:
        raise PackagingRenderError(
            "root pyproject.toml is missing [project] version"
        ) from exc
    if not isinstance(version, str) or not version:
        raise PackagingRenderError("root [project] version must be a non-empty string")
    return version


def _render_host_pyproject(version: str) -> str:
    return f"""# Generated by scripts/render_packaging.py; edit the root pyproject [project] version, then run `make render-packaging`.
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solstone-journal-host"
description = "solstone journal-host console scripts (journal, mlx-vlm-server)"
readme = {{text = "Host-only console scripts (journal, mlx-vlm-server) for a solstone journal host. Installed via solstone[journal]. See https://github.com/solpbc/solstone-journal.", content-type = "text/markdown"}}
version = "{version}"
requires-python = ">=3.12"
dependencies = [
    "solstone[journal-host]=={version}",
]

[project.scripts]
journal = "solstone.think.sol_cli:journal_main"
mlx-vlm-server = "solstone.think.providers.mlx_server:main"

[tool.setuptools]
packages = []
py-modules = []

[tool.uv.sources]
solstone = {{workspace = true}}
"""


def _replace_host_pin(array_body: str, *, extra: str, version: str) -> str:
    matches = list(HOST_PIN_RE.finditer(array_body))
    if len(matches) != 1:
        raise PackagingRenderError(
            f"[project.optional-dependencies].{extra} must contain exactly one "
            f"solstone-journal-host== pin; found {len(matches)}"
        )
    return HOST_PIN_RE.sub(f'"solstone-journal-host=={version}"', array_body)


def _rewrite_extra_pin(section_body: str, *, extra: str, version: str) -> str:
    pattern = re.compile(ARRAY_RE_TEMPLATE.format(name=re.escape(extra)))
    match = pattern.search(section_body)
    if not match:
        raise PackagingRenderError(
            f"root pyproject.toml is missing [project.optional-dependencies].{extra}"
        )
    rewritten_body = _replace_host_pin(
        match.group("body"),
        extra=extra,
        version=version,
    )
    rewritten_array = match.group("prefix") + rewritten_body + match.group("suffix")
    return section_body[: match.start()] + rewritten_array + section_body[match.end() :]


def _rewrite_root_pyproject(pyproject_text: str, version: str) -> str:
    match = OPTIONAL_DEPS_RE.search(pyproject_text)
    if not match:
        raise PackagingRenderError(
            "root pyproject.toml is missing [project.optional-dependencies]"
        )

    section_body = match.group("body")
    section_body = _rewrite_extra_pin(section_body, extra="journal", version=version)
    section_body = _rewrite_extra_pin(
        section_body,
        extra="journal-cuda",
        version=version,
    )
    return (
        pyproject_text[: match.start("body")]
        + section_body
        + pyproject_text[match.end("body") :]
    )


def _write_if_changed(path: Path, content: str) -> None:
    old_content = path.read_text(encoding="utf-8") if path.exists() else None
    if old_content == content:
        LOGGER.info("%s already up to date", path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    LOGGER.info("wrote %s", path)


def _drifted(path: Path, expected: str) -> bool:
    try:
        current = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return True
    return current != expected


def render() -> tuple[str, str]:
    root_text = ROOT_PYPROJECT.read_text(encoding="utf-8")
    version = _read_version(root_text)
    return (
        _rewrite_root_pyproject(root_text, version),
        _render_host_pyproject(version),
    )


def check(root_pyproject: str, host_pyproject: str) -> int:
    drifted = [
        str(path.relative_to(ROOT))
        for path, expected in (
            (ROOT_PYPROJECT, root_pyproject),
            (HOST_PYPROJECT, host_pyproject),
        )
        if _drifted(path, expected)
    ]
    if drifted:
        print("packaging metadata is stale; run python3 scripts/render_packaging.py")
        for path in drifted:
            print(f"  drifted: {path}")
        return 1
    print("packaging metadata is up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated packaging metadata is not up to date",
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    try:
        root_pyproject, host_pyproject = render()
        if args.check:
            return check(root_pyproject, host_pyproject)
        _write_if_changed(ROOT_PYPROJECT, root_pyproject)
        _write_if_changed(HOST_PYPROJECT, host_pyproject)
    except PackagingRenderError as exc:
        LOGGER.error("%s", exc)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
